import * as React from 'react';
import Head from 'next/head';
import axios from 'axios';
import {GetStaticProps, GetStaticPaths} from 'next';
import { AppProps } from 'next/dist/shared/lib/router/router';
import { useState , useEffect} from 'react';
import { useRouter } from 'next/router';
import {getBlogIds, getBlogById } from '../../components/lib/blog';
import blog from '.';
export const getStaticPaths:GetStaticPaths = async () => {
	const paths = await getBlogIds();
	console.log(paths);
	return {
		paths,
		fallback: false // bat ki path nao ko returned boi getpath se dan den page 404
	}
}
export const getStaticProps = async ({params}) => {
	const blog = await getBlogById(params.id);
	return { 
		props: {
			blog
		}
	}
}
const Blog:React.FC<AppProps> = (props) => {
	const {data} = props.blog;
	console.log(blog);
	return (
		<div>
			<Head>
				<title>Blog</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='wrap'>
				<div className='blog'>
				</div>
					<div className='blog'>
						<div className='cardTitle'>
							<span>SIMPLE BLOG</span>
							<div></div>
						</div>
						<div className='blogContent' key={data.id}>
							<h5>
								{data.title}
							</h5>
							<img src={`http://localhost/laravel/public/upload/Blog/image/${data.image}`} alt="" />
							<p>
								{data.description}
								{data.description}
								{data.description}
								{data.description}
							</p>
						</div>
				</div>
			</main>
		</div>
	);
}
export default Blog;