import * as React from 'react';
import Head from 'next/head';
import axios from 'axios';
import {GetStaticProps} from 'next';
import { AppProps } from 'next/dist/shared/lib/router/router';
import { useState } from 'react';
import Link from 'next/link';
export const getStaticProps:GetStaticProps = async () => {
	const url: string = 'http://localhost/laravel/public/api/blog'
	const res = await axios.get(url);
	if(!res.data) {
		return {
      notFound: true,
    }
	}
	return {
		props: {
			data: res.data
		}
	}
}
const Blog:React.FC<AppProps> = (data) => {
	const [blogs, setBlogs] = useState(data.data.blog);
	return (
		<div>
			<Head>
				<title>Home Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='wrap'>
				<div className='blog'>
				</div>
					<div className='blog'>
						<div className='cardTitle'>
							<span>LATEST FROM OUR BLOG</span>
							<div></div>
						</div>
						{
							blogs.data.map((val, i) => {
								return<div className='blogContent' key={val.id}>
										<h5>
											{val.title}
										</h5>
										<img src={`http://localhost/laravel/public/upload/Blog/image/${val.image}`} alt="" />
										<p>
											{val.description}
										</p>
										<Link href={`/blog/${val.id}`}>
											<button type="button" className="btn btn-outline-primary" data-mdb-ripple-color="dark">
												Read more
											</button>
										</Link>
									</div>
							})
						}
				</div>
			</main>
		</div>
	);
}
export default Blog;
// tsdrpfc